version: "3"

## PORT allocation scheme:
# 1th digit: Service type: (0 = db, 1 = api)
# 2nd digit: Layer number (1 = l1, 2 = l2)
# 3rd digit: ID of service [since multiple services like hospitals, states can exist] (>= 1)
# 4th digit: Level of service (1 = local, 2 = state, 3 = national)
# 5th digit: HealthChain service identifier (1xxxx)
# Example: 12120 = 'DB' of 'Layer 2' of 'ID 1' at 'State Level', 'Healthchain'

services:
    mongo.l1.id1.local.healthchain.com:
        image: mongo:5.0.9
        ports:
            - "11110:27017"

    api.l1.id1.local.healthchain.com:
        extends:
            file: ./local/docker-compose.yml
            service: l1-api
        ports:
            - "11111:3000"
        links:
            - mongo.l1.id1.local.healthchain.com

    api.l2.id1.local.healthchain.com:
        extends:
            file: ./local/docker-compose.yml
            service: l2-api
        ports:
            - "11121:3000"

    mongo.l1.id2.local.healthchain.com:
        image: mongo:5.0.9
        ports:
            - "11210:27017"

    api.l1.id2.local.healthchain.com:
        extends:
            file: ./local/docker-compose.yml
            service: l1-api
        ports:
            - "11211:3000"
        links:
            - mongo.l1.id2.local.healthchain.com

    api.l2.id2.local.healthchain.com:
        extends:
            file: ./local/docker-compose.yml
            service: l2-api
        ports:
            - "11221:3000"

    mongo.l1.id1.state.healthchain.com:
        image: mongo:5.0.9
        ports:
            - "12110:27017"

    api.l1.id1.state.healthchain.com:
        extends:
            file: ./state/docker-compose.yml
            service: l1-api
        ports:
            - "12111:3000"
        links:
            - mongo.l1.id1.state.healthchain.com

    api.l2.id1.state.healthchain.com:
        extends:
            file: ./state/docker-compose.yml
            service: l2-api
        ports:
            - "12121:3000"

    mongo.l1.id1.national.healthchain.com:
        image: mongo:5.0.9
        ports:
            - "13110:27017"

    api.l1.id1.national.healthchain.com:
        extends:
            file: ./state/docker-compose.yml
            service: l1-api
        ports:
            - "13111:3000"
        links:
            - mongo.l1.id1.state.healthchain.com

    api.l2.id1.national.healthchain.com:
        extends:
            file: ./national/docker-compose.yml
            service: l2-api
        ports:
            - "13121:3000"
