version: "3"

volumes:
    orderer.blc.healthchain.com:

networks:
    healthnet:

services:
    orderer.blc.healthchain.com:
        extends:
            file: $PWD/blockchain/docker/common/orderer-base.yml
            service: orderer-base
        environment:
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_OPERATIONS_LISTENADDRESS=orderer.blc.healthchain.com:9443
            - GRPC_VERBOSITY=DEBUG
        volumes:
            - $PWD/blockchain/gen/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - $PWD/blockchain/gen/organizations/ordererOrganizations/blc.healthchain.com/orderers/orderer.blc.healthchain.com/msp:/var/hyperledger/orderer/msp
            - $PWD/blockchain/gen/organizations/ordererOrganizations/blc.healthchain.com/orderers/orderer.blc.healthchain.com/tls/:/var/hyperledger/orderer/tls
            - orderer.blc.healthchain.com:/var/hyperledger/production/orderer
        depends_on:
            - ca.id1.local.healthchain.com
            - ca.id2.local.healthchain.com
            - ca.id1.state.healthchain.com
            - ca.id1.national.healthchain.com
        ports:
            - 7050:7050
            - 9443:9443
        networks:
            - healthnet

    cli.blc.healthchain.com:
        extends:
            file: $PWD/blockchain/docker/common/cli-base.yml
            service: cli-base
        environment:
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.id1.national.healthchain.com:13132
            - CORE_PEER_LOCALMSPID=NationalMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/id1.national.healthchain.com/peers/peer0.id1.national.healthchain.com/tls/ca.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/id1.national.healthchain.com/peers/peer0.id1.national.healthchain.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/id1.national.healthchain.com/peers/peer0.id1.national.healthchain.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/id1.national.healthchain.com/users/Admin@id1.national.healthchain.com/msp
        volumes:
            - /var/run/:/host/var/run/
            - $PWD/blockchain/gen/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
            - $PWD/blockchain/scripts/container:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - $PWD/blockchain/gen/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
            - $PWD/blockchain/contracts:/usr/local/go/src/
        depends_on:
            - orderer.blc.healthchain.com
            - peer0.id1.local.healthchain.com
            - peer0.id2.local.healthchain.com
            - peer0.id1.state.healthchain.com
            - peer0.id1.national.healthchain.com
        networks:
            - healthnet
