version: "3"

volumes:
    peer0.id2.local.healthchain.com:

networks:
    healthnet:

## PORT allocation scheme:
# 1th digit: Service type: (0 = db, 1 = api, 2 = peer, 3 = fabric-api, 4 = chaincode, 5 = ca)
# 2nd digit: Layer number (1 = l1, 2 = l2, 3 = blockchain)
# 3rd digit: ID of service [since multiple services like hospitals, states can exist] (>= 1)
# 4th digit: Level of service (1 = local, 2 = state, 3 = national, 4 = orderer)
# 5th digit: HealthChain service identifier (1xxxx)
# Example: 12120 = 'DB' of 'Layer 2' of 'ID 1' at 'State Level', 'Healthchain'

services:
    db.blc.id2.local.healthchain.com:
        extends:
        file: $PWD/docker/common/api-auth-db.yml
        service: mongo
        networks:
            - healthnet
        volumes:
            - $PWD/generated/db.blc.id2.local.healthchain.com:/data/db

    api.blc.id2.local.healthchain.com:
        extends:
            file: $PWD/blockchain/docker/common/api-base.yml
            service: fabric-api
        environment:
            - ORG_NAME=id2.local
            - ORG_MSP=Local2MSP
            - MONGODB_URI=db.blc.id2.local.healthchain.com:27017
        volumes:
            - $PWD/blockchain/gen/organizations/peerOrganizations/id2.local.healthchain.com:/crypto
        ports:
            - 11233:3000
        depends_on:
            - peer0.id2.local.healthchain.com
            - ca.id2.local.healthchain.com
        networks:
            - healthnet
        links:
            - db.blc.id2.local.healthchain.com

    peer0.id2.local.healthchain.com:
        extends:
            file: $PWD/blockchain/docker/common/peer-base.yml
            service: peer-base
        environment:
            # Peer specific variabes
            - CORE_PEER_ID=peer0.id2.local.healthchain.com
            - CORE_PEER_ADDRESS=peer0.id2.local.healthchain.com:11232
            - CORE_PEER_LISTENADDRESS=0.0.0.0:11232
            - CORE_PEER_CHAINCODEADDRESS=peer0.id2.local.healthchain.com:11234
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11234
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.id2.local.healthchain.com:11232
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.id2.local.healthchain.com:11232
            - CORE_PEER_LOCALMSPID=Local2MSP
            - GRPC_VERBOSITY=DEBUG
            - CORE_OPERATIONS_LISTENADDRESS=peer0.id2.local.healthchain.com:11236
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - $PWD/blockchain/gen/organizations/peerOrganizations/id2.local.healthchain.com/peers/peer0.id2.local.healthchain.com/msp:/etc/hyperledger/fabric/msp
            - $PWD/blockchain/gen/organizations/peerOrganizations/id2.local.healthchain.com/peers/peer0.id2.local.healthchain.com/tls:/etc/hyperledger/fabric/tls
            - peer0.id2.local.healthchain.com:/var/hyperledger/production
        ports:
            - 11232:11232
            - 11236:11236
        networks:
            - healthnet

    ca.id2.local.healthchain.com:
        extends:
            file: $PWD/blockchain/docker/common/ca-base.yml
            service: ca-base
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca.id2.local.healthchain.com
            - FABRIC_CA_SERVER_PORT=11235
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.id2.local.healthchain.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
        ports:
            - "11235:11235"
        volumes:
            - $PWD/blockchain/gen/fabric-ca/id2.local.healthchain.com:/etc/hyperledger/fabric-ca-server
            - $PWD/blockchain/gen/organizations/peerOrganizations/id2.local.healthchain.com/ca:/etc/hyperledger/fabric-ca-server-config
        networks:
            - healthnet
