version: "3"

volumes:
    orderer.blc.healthchain.com:

networks:
    healthnet:

services:
    orderer.blc.healthchain.com:
        extends:
            file: ./common/orderer-base.yml
            service: orderer-base
        volumes:
            - ../gen/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ../gen/organizations/ordererOrganizations/blc.healthchain.com/orderers/orderer.blc.healthchain.com/msp:/var/hyperledger/orderer/msp
            - ../gen/organizations/ordererOrganizations/blc.healthchain.com/orderers/orderer.blc.healthchain.com/tls/:/var/hyperledger/orderer/tls
            - orderer.blc.healthchain.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050
            - 9443:9443
        networks:
            - healthnet

    cli.blc.healthchain.com:
        extends:
            file: ./common/cli-base.yml
            service: cli-base
        volumes:
            - /var/run/:/host/var/run/
            - ../gen/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
            - ../gen/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        depends_on:
            - orderer.blc.healthchain.com
            - peer0.id1.local.healthchain.com
            - peer0.id2.local.healthchain.com
            - peer0.id1.state.healthchain.com
            - peer0.id1.national.healthchain.com
        networks:
            - healthnet
