version: "3"

volumes:
    peer0.id1.local.healthchain.com:

networks:
    healthnet:

## PORT allocation scheme:
# 1th digit: Service type: (0 = db, 1 = api, 2 = peer, 3 = fabric-api, 4 = chaincode, 5 = ca)
# 2nd digit: Layer number (1 = l1, 2 = l2, 3 = blockchain)
# 3rd digit: ID of service [since multiple services like hospitals, states can exist] (>= 1)
# 4th digit: Level of service (1 = local, 2 = state, 3 = national, 4 = orderer)
# 5th digit: HealthChain service identifier (1xxxx)
# Example: 12120 = 'DB' of 'Layer 2' of 'ID 1' at 'State Level', 'Healthchain'

services:
    api.blc.id1.local.healthchain.com:
        extends:
            file: ./common/api-base.yml
            service: fabric-api
        environment:
            - ORG_NAME=id1.local
            - ORG_MSP=Local1MSP
        volumes:
            - ../gen/organizations/peerOrganizations/id1.local.healthchain.com:/crypto
        ports:
            - 11133:3000
        depends_on:
            - peer0.id1.local.healthchain.com
            - ca.id1.local.healthchain.com
        networks:
            - healthnet

    peer0.id1.local.healthchain.com:
        extends:
            file: ./common/peer-base.yml
            service: peer-base
        environment:
            # Peer specific variabes
            - CORE_PEER_ID=peer0.id1.local.healthchain.com
            - CORE_PEER_ADDRESS=peer0.id1.local.healthchain.com:11132
            - CORE_PEER_LISTENADDRESS=0.0.0.0:11132
            - CORE_PEER_CHAINCODEADDRESS=peer0.id1.local.healthchain.com:11134
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11134
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.id1.local.healthchain.com:11132
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.id1.local.healthchain.com:11132
            - CORE_PEER_LOCALMSPID=Local1MSP
            - GRPC_VERBOSITY=DEBUG
            - CORE_OPERATIONS_LISTENADDRESS=peer0.id1.local.healthchain.com:11136
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../gen/organizations/peerOrganizations/id1.local.healthchain.com/peers/peer0.id1.local.healthchain.com/msp:/etc/hyperledger/fabric/msp
            - ../gen/organizations/peerOrganizations/id1.local.healthchain.com/peers/peer0.id1.local.healthchain.com/tls:/etc/hyperledger/fabric/tls
            - peer0.id1.local.healthchain.com:/var/hyperledger/production
        ports:
            - 11132:11132
            - 11136:11136
        networks:
            - healthnet

    ca.id1.local.healthchain.com:
        extends:
            file: ./common/ca-base.yml
            service: ca-base
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca.id1.local.healthchain.com
            - FABRIC_CA_SERVER_PORT=11135
        ports:
            - "11135:11135"
        volumes:
            - ../gen/fabric-ca/id1.local.healthchain.com:/etc/hyperledger/fabric-ca-server
        networks:
            - healthnet
