version: "3"

services:
    ca-base:
        image: hyperledger/fabric-ca:2.2
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            # - FABRIC_CA_SERVER_CA_NAME=ca-org3
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            # - FABRIC_CA_SERVER_PORT=11054
        # ports:
        #     - "11054:11054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        # volumes:
        #     - ../fabric-ca/org3:/etc/hyperledger/fabric-ca-server
