version: "3"

networks:
    healthnet:

## PORT allocation scheme:
# 1th digit: Service type: (0 = db, 1 = api)
# 2nd digit: Layer number (1 = l1, 2 = l2)
# 3rd digit: ID of service [since multiple services like hospitals, states can exist] (>= 1)
# 4th digit: Level of service (1 = local, 2 = state, 3 = national)
# 5th digit: HealthChain service identifier (1xxxx)
# Example: 12120 = 'DB' of 'Layer 2' of 'ID 1' at 'State Level', 'Healthchain'

services:
    # Local Level Services for State-1
    ## Local Service 1 (State-1)
    db.l1.id1.local.healthchain.com:
        extends:
            file: $PWD/docker/common/docker-compose-db.yml
            service: mongo
        networks:
            - healthnet
        volumes:
            - $PWD/generated/db.l1.id1.local.healthchain.com:/data/db

    api.l1.id1.local.healthchain.com:
        image: api.l1.local.healthchain.com
        networks:
            - healthnet
        ports:
            - "11111:3000"
        links:
            - db.l1.id1.local.healthchain.com
        environment:
            - MONGODB_URI=db.l1.id1.local.healthchain.com:27017
            - NODE_PREFIX=id1.local

    api.l2.id1.local.healthchain.com:
        image: api.l2.local.healthchain.com
        networks:
            - healthnet
        ports:
            - "11121:3000"
        environment:
            - L1_API=api.l1.id1.local.healthchain.com:3000
            - NODE_ID=id1
            - NODE_PREFIX=id1.local
            - NODE_NAME=Hospital 1 State 1
            - NODE_STATE_ID=id1
            - REGISTRY_API=api.registry.healthchain.com:3000
        depends_on:
            - api.l2.id1.state.healthchain.com
