################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &id1.local.healthchain.com
      # DefaultOrg defines the organization which is used in the sampleconfig
      # of the fabric.git development environment
      Name: Local1MSP

      # ID to load the MSP definition as
      ID: Local1MSP

      MSPDir: ../organizations/peerOrganizations/id1.local.healthchain.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Local1MSP.admin', 'Local1MSP.peer', 'Local1MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('Local1MSP.admin', 'Local1MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('Local1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Local1MSP.peer')"
