# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
    - Name: Local2
      Domain: id2.local.healthchain.com
      EnableNodeOUs: true
      Template:
          Count: 1
          SANS:
              - peer0.id2.local.healthchain.com
      Users:
          Count: 1
