# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
    - Name: Local1
      Domain: id1.local.healthchain.com
      EnableNodeOUs: true
      Template:
          Count: 1
          SANS:
              - localhost
      Users:
          Count: 1
