# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
    - Name: National
      Domain: id1.national.healthchain.com
      EnableNodeOUs: true
      Template:
          Count: 1
          SANS:
              - localhost
      Users:
          Count: 1
