# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
    - Name: State1
      Domain: id1.state.healthchain.com
      EnableNodeOUs: true
      Template:
          Count: 1
          SANS:
              - peer0.id1.state.healthchain.com
      Users:
          Count: 1
